import { Button, VerticalBox, LineEdit } from "std-widgets.slint";



export component AppWindow inherits Window {

    in property <string> results: "";
    callback divide-income(string);

    background: #313e50;
    GridLayout {
        padding: 50px;   
        spacing: 25px; 
        Row {
            Text {
                text: "输入总收入";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "输入数字";
                height: 35px;

            }
        }

        Row {
            Button {
                text: "计算";
                primary: true;
                height: 35px;
                clicked => {
                    divide-income(income.text);
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
